name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    name: jdk-${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"
      - name: "Build"
        run: mvn --batch-mode -no-transfer-progress -V verify
        env:
          JDK_JAVA_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED
  flaky:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Clean Install
        run: mvn clean install -DskipTests
      - name: Build Module
        run: mvn clean install -DskipTests -pl . -am
      - name: Scan for Flaky Test
        run: mvn -pl . edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.hubspot.jinjava.lib.tag.eager.EagerImportTagTest#itDefersTripleLayer